import './globals.css'
import type { Metadata } from 'next'

import { inter, zen_kaku_gothic_new } from './font'


import CountProvider from './countProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
    <body className={zen_kaku_gothic_new.className}><CountProvider>{children}</CountProvider></body>
    </html>
  )
}
